### ISSUE TITLE
Synchronize photo and marker when navigating the sequence from the right panel

### ISSUE THREAD

**Issue by govvin** [tankaru/mapillarySequenceStraightener#1]
Hey, this is a great utility for Mapillary images! Domo arigato. :)

When I left click on a marker on the left panel, the corresponding photo will display on the right panel.

But when I navigate (e.g. move forward or backward) through the sequence on the right panel, the selected marker doesn't change.

I think it would be helpful if they synchronize, for example when I"m trying to find the correct photo in the sequence to set as the "corner photo".

**Comment by tankaru** [comment]
Marker selection and viewer are synchronized.
However it requires heavy duty, so smooth transition is cancelled on my PC, maybe.

**Comment by tankaru** [comment]
Smooth transition is recovered.

**Comment by govvin** [comment]
Excellent! It works as expected. 

Thank you very much.
