### ISSUE TITLE
tool doesn't work in this particular sequence, no error messages.

### ISSUE THREAD

**Issue by govvin** [tankaru/mapillarySequenceStraightener#4]
![image](https://user-images.githubusercontent.com/5821688/78614046-0c9df380-78a0-11ea-8ce8-cb4468ae7206.png)

Start and End points already set, but clicking on straighten button doesn't do anything.

The sequence id is: `4efefHKxfaNasf6fTalfYw`

**Comment by govvin** [comment]
Hmm ... this is weird. It's also not working with sequence id: `CzQFtNGTvV4Kg5XljY09ow`

**Comment by tankaru** [comment]
would you set "Corner" by left-click?
![image](https://user-images.githubusercontent.com/13701091/78615396-5987c700-78ac-11ea-87e6-419e69092dce.png)

**Comment by govvin** [comment]
hmmm .. i may have missed that. Thank you.
